name: Run Video Bot

on:
  workflow_dispatch: # Позволяет запускать вручную кнопкой
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install yt-dlp openai-whisper moviepy==1.0.3 python-dotenv python-telegram-bot feedparser torch


      - name: Run Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
